### ISSUE TITLE
modded armor skining and resorcepack not rendering proply version 3.2

### ISSUE THREAD

**Issue by calvincolt123** [MineLittlePony/MineLittlePony#109]
![2019-02-22_13 43 55](https://user-images.githubusercontent.com/21012793/53246548-f5ef0a00-36a8-11e9-9609-79f4214c4ae6.png)
![2019-02-22_13 28 00](https://user-images.githubusercontent.com/21012793/53246554-f7b8cd80-36a8-11e9-8000-f85aad3ea7ce.png)

**Comment by Sollace** [comment]
@calvincolt123 Can you add more details, please?

I could use the mods, resourcepacks, and skins being used, and what they should look like versus how they do.

**Comment by hectorskypl** [comment]
Sure thing, here is a issue, every moded armor i render not properly.

**Comment by ModernSilver** [comment]
@Sollace just thought I'd ask, did you ever figure out what was going on with this? It looks to me that (s)he's just not using any mlp compatible armor files. In my experience, modded armor works, but it doesn't work out of the box, you have to patch it manually.

I have quite a few hd pixelmon armors that do work with Mine Little Pony. If I can get that to work, then any modded armor should be able to work with mlp if patched properly, some just require more work than others, double that if you're doing hd.

@hectorskypl Are you using any modified assets for the modded armor in a resource pack?

**Comment by Sollace** [comment]
I'm going to close this as inactive for now. We've had no responses from the original post (@calvincolt123 ) in four months since the thread was created, and as we're on 1.14.3 the situation may have changed drastically since then.

If the problem persists and anyone can reproduce it in _current_ versions of the mod, I kindly ask that they submit a new issue.
