### ISSUE TITLE
Can't use optifine and optifine fabric

### ISSUE THREAD

**Issue by zuzu428** [MineLittlePony/MineLittlePony#200]
when i use optifine Pony skins cannot be loaded and pony skins cannot be changed

**Comment by MimzyFang** [comment]
OptiFine doesn't support Fabric natively and is widely known to cause compatibility issues with other mods, including Mine Little Pony, because of this.
For that reason we do not recommend using it if at all possible.

For performance, use: https://www.curseforge.com/minecraft/mc-mods/sodium
For Shaders, use: https://irisshaders.net/

These mods, among others that replace Optifine's features, can be found on this list here:
https://lambdaurora.dev/optifine_alternatives

**Comment by zuzu428** [comment]
thank you i know all this but it used to work on optifine ... The reason I use optifine is because I want to use CIT pack .And I like the feeling of light and shadow. Only optifine can see cit ...Is there any way I can use the pony mod and cit pack at the same time?

**Comment by MimzyFang** [comment]
I don't know if it will work how you want it to work but maybe this helps:
https://modrinth.com/mod/cit-resewn

**Comment by MimzyFang** [comment]
> I don't know if it will work how you want it to work but maybe this helps:
> https://modrinth.com/mod/cit-resewn

It's from the list of optifine alternatives
