### ISSUE TITLE
Head and Head Armor disconnected from model while laying down 

### ISSUE THREAD

**Issue by AdamDash** [MineLittlePony/MineLittlePony#259]
During the new lay-down sneak animation the head and the ponies armor appears disconnected from the body.

![2023-12-19_11 26 57](https://github.com/MineLittlePony/MineLittlePony/assets/65252885/f6f3a16c-824f-48ae-ba28-ce6e81680757)
![2023-12-19_11 26 48](https://github.com/MineLittlePony/MineLittlePony/assets/65252885/0b27797a-d3a6-4383-a4df-6031692a8172)

**Comment by Sollace** [comment]
This isna bug I'm aware of. Thanks for reporting it.

**Comment by AdamDash** [comment]
of course

**Comment by Sollace** [comment]
Can you test this in the new release? I couldn't reproduce it in dev.

**Comment by AdamDash** [comment]
The bug still exists for me in the new version. This is more of a suggestion, but I think it might be nice to have a toggle to make the lay-down sneak animation optional because I personally prefer the sneak animation how it used to work.

**Comment by Sollace** [comment]
> The bug still exists for me in the new version. This is more of a suggestion, but I think it might be nice to have a toggle to make the lay-down sneak animation optional because I personally prefer the sneak animation how it used to work.

![image](https://github.com/MineLittlePony/MineLittlePony/assets/6429283/e96df238-1f8e-46f8-bf8a-6b41aa106dcb)

Do you have any other mods present?

**Comment by AdamDash** [comment]
I do have other mods present, but I have tested the mod with only HD skins, Kirin, and the fabric API and the problem persists. I also tried without HD skins and the models it was the same. Here is a list of the mods I have installed and pictures of the bug.
![Screenshot 2024-02-22 180913](https://github.com/MineLittlePony/MineLittlePony/assets/65252885/351c4a2a-bf4a-4ac1-92ce-cc02b0f68cf8)
![2024-02-22_18 06 09](https://github.com/MineLittlePony/MineLittlePony/assets/65252885/aea62f7b-d7b6-4c59-8a69-0102e3a0bc95)
![2024-02-22_18 08 23](https://github.com/MineLittlePony/MineLittlePony/assets/65252885/1127760f-4e93-4e55-96eb-be8e655cfb40)

**Comment by Sollace** [comment]
This isn't just the head that's offset, it's the entire armor layer that's shifted down by a few pixels.

You have a mix of 1.20.1, 1.20.2, and 1.20.4 mods. My testing was done on 1.20.1. Does your problem go away if you downgrade to that version?

**Comment by AdamDash** [comment]
I downgraded to the 1.20.1 version of the mod (v. 4.10.4) and that fixed did fix the problem, but the problem still exists in version 1.20.4 on the version 4.11.6 of the mod.

**Comment by MimzyFang** [comment]
fabric 1.20.4:
![grafik](https://github.com/MineLittlePony/MineLittlePony/assets/43648117/a51152fd-f41a-496c-88cb-37794ba36ccc)

here is the log so that you have the exact version I'm running on https://mclo.gs/eY3J5nG

fabric 1.20.2:
![grafik](https://github.com/MineLittlePony/MineLittlePony/assets/43648117/97b51e14-14a2-4373-a42e-b6ff89838d25)

here is my log for the exact version of everything as well https://mclo.gs/nPQvQgJ

quilt 1.20.2:
![grafik](https://github.com/MineLittlePony/MineLittlePony/assets/43648117/8fdefc8d-4195-4f9b-8bcf-e73bc958e710)

and the log https://mclo.gs/dWlCT6Y

fabric 1.20.1:
![grafik](https://github.com/MineLittlePony/MineLittlePony/assets/43648117/c4c5e783-afb7-4d09-a65f-54f26e6f3618)

log https://mclo.gs/t8eNdB0

quilt 1.20.1:

![grafik](https://github.com/MineLittlePony/MineLittlePony/assets/43648117/9b8162a5-02f7-4013-b216-34589ed8e791)

https://mclo.gs/Mk666fA

also I have to apologize I was bored

**Comment by Sollace** [comment]
This should have been closed. I don't know why it's still open

**Comment by MimzyFang** [comment]
@Sollace the neck is still weird even in the latest release

**Comment by Sollace** [comment]
*head position

Whoops
