### ISSUE TITLE
Some pony skin textures are not textured or displayed correctly

### ISSUE THREAD

**Issue by Herobrine7707** [MineLittlePony/MineLittlePony#281]
hi, I've been playing the mod for years and think it's cool. However, some pony skins are not displayed correctly for the player. I tried it with the foal pony skins. I took and edited a screenshot that shows two different pictures        

![Minecraft_ 1 20 6 - Einzelspieler 21 05 2024 11_31_02](https://github.com/MineLittlePony/MineLittlePony/assets/87422017/7fdb9ec1-2121-46e7-8d28-7f4af2b871cc)

There you can see two examples that show what I mean very well, you can see it on the legs, hence the view of the feet The incorrect textures of the foals also exist in older versions

minecraft version:1.20.6
modloader:fabric

**Comment by Sollace** [comment]
You're playing with the alex model type.

If you uploaded the skin using hd skins, go back to the uploader and make sure you set the body type to "steve" and upload it again.
If you're using mojang's website, you have to select the "classic" model before you upload your skin.

![image](https://github.com/MineLittlePony/MineLittlePony/assets/6429283/e8d1fc67-4ebb-4255-93a0-e18d7e3c89ba)

Otherwise you need to modify your skin to work with the slim legs if you want to play like that.
