### ISSUE TITLE
Issues with skins for Fabric 1.20.1

### ISSUE THREAD

**Issue by Dragunsblood** [MineLittlePony/MineLittlePony#288]
**Describe the bug**
Several issues regarding skins are present in the fabric 1.20.1 version. Sea pony skins do not display properly in the hd skin menu, only showing the basic pony model. armor and elytra create a large black square on the front of the pony. additionally, the pants icon for hd skins does not appear, and mod menu must be installed or the mod becomes unusable. 

**Expected behavior**
Seapony skins should show up with the correct model, and armor should not be creating black boxes on players. the hd skin menu should be accessible on the main menu. 

**Steps to reproduce**
download mine little pony, hd skin menu, big pony, fabric api, and unicopia. attempt to access the hd skin menu. if mod menu is installed, attempt to see the seapony body shape. in game, put on a piece of armor.

**Version Information:**
 - Minecraft Version: 1.20.1
 - Mine Little Pony Version: 4.11.7

**Mod Loader:**
 - [X] Fabric
 - [ ] Quilt
 - [ ] Neoforge (with connector)

**Client/Server Logs**
N/A

**Comment by MimzyFang** [comment]
What other mods do you have and can you share you're skin with us?

**Comment by Dragunsblood** [comment]
> What other mods do you have and can you share you're skin with us?

tested this with an instance using only big pony, hd skins, unicopia, and mine little pony other than the fabric api.
skins:
![charpony](https://github.com/user-attachments/assets/8bd60edc-4152-4c79-aa3e-67d9f5bb5708)
![seapony](https://github.com/user-attachments/assets/a0fa2960-dd77-4eda-94c2-7397be424d69)

**Comment by Dragunsblood** [comment]
downloaded mod menu to get some screenshots. the one of the armor is also how it appears in game.
![1](https://github.com/user-attachments/assets/6e1d27e4-05f4-4200-8dbc-a13490b3c1c2)
![2](https://github.com/user-attachments/assets/0579baca-903a-49a4-806b-89636b6856d5)

**Comment by Sollace** [comment]
The black square is a bug with unicopia which is going to be fixed with the new update.

The pants button is part of HD Skins, so not part of this mod and it's a known issue with the config. You can still access it via Mine Little Pony's settings or by pressing the shortcut key.

Seaponies might be broken because of server changes in how the skin type is identified. I usually leave that up to @mattmess1221 as that's their expertise. Clients using the old version of the api (like 1.20.1 was using if I remember correctly) should still be working based on what they've told me.

**Comment by Sollace** [comment]
Most of these are fixed by updating unicopia
