### ISSUE TITLE
No compilation instructions in README.md

### ISSUE THREAD

**Issue by avrildev** [MineLittlePony/MineLittlePony#30]
Maybe it's obvious for Minecraft modder pros, but I personally struggled to figure out how to compile this. The gradle script is pretty self explanatory, but I  can imagine people newer to project builds (or Java projects) would have no idea what to do.

Furthermore, it compiles for 1.11 by default, and I can't quite figure out how to get it to compile for 1.10.2. I've tried changing around some config files, but that only resulted in compilation errors I didn't understand.

Maybe it'd be a good idea to write some brief compilation instructions to point noobs like me in the right direction in situations like this?

**Comment by killjoy1221** [comment]
Building is the same for literally every minecraft mod.
```shell
gradle setupDecompWorkspace
gradle build
```

As for compiling for 1.10, that is not how this works. I target a single
version of minecraft at a time, so compilation errors are expected when you
switch versions. 1.11 has some classes I reference which aren't in 1.10.
Also, 1.11 changed how villager professions work, so that would need to be
accounted for.

Anyway, you can build for 1.10 if you want, but I suggest using the 1.10
branch. It's a little behind master, but it's written for 1.10.

**Comment by avrildev** [comment]
@killjoy1221 Ah, sorry. I didn't realize there was a different branch for that sort of thing. I just thought the build system dynamically switched between modules of code intended for different version of MC, or something. I'll use the 1.10 branch.

I guess if I'm the only one who ever brought this up, then maybe it doesn't cause as much confusion as I would have expected.

Thanks for being patient with my noobiness. :P
