### ISSUE TITLE
neither 1.11.2 release seems to work with Llibrary.

### ISSUE THREAD

**Issue by PlanetKiller** [MineLittlePony/MineLittlePony#38]
This is just a minor inconvenience to me, but the 1.11.2 versions will not work with Llibrary. Tried both with Jurassicraft, liteloader, forge, and Llibrary. 

Jurassicraft depends upon Llibrary. I don't need any potato about MLP not needing Llibrary, I'm using that mod for Jurassicraft. I know MLP does not depend on Llibray.

This means I cannot have a pony eating tyrannosaurs. I just wanted to alert you to this possibility, already informed the developer of Llibrary and tested to make sure this was the case. I'll just put together two different packs, but a fix would be nice. Thanks.
[crash-2017-10-04_16.35.08-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/1357423/crash-2017-10-04_16.35.08-client.txt)

**Comment by killjoy1221** [comment]
I've looked at the source code for LLibrary, and it looks like he does some funky stuff as a coremod. This stuff makes it impossible to easily fix.

Although, if LLibrary were to switch to using Mixins instead of his own asm library, some compatibility would be easier to achieve. Have you created an issue on the [LLibrary repo](https://github.com/iLexiconn/LLibrary) yet?

**Comment by PlanetKiller** [comment]
Yeah, they know. Thanks for looking into it.

**Comment by killjoy1221** [comment]
We've recently had a huge refactor (unreleased) so we no longer replace the player renderer. Can you say whether this is fixed now?

**Comment by Sollace** [comment]
Closing this. I assume if it still applied to 1.14+ a new issue will be created.
