### ISSUE TITLE
Custom skin uploading non-functional

### ISSUE THREAD

**Issue by ConnorWM18** [MineLittlePony/MineLittlePony#76]
I did a bit if digging to see if I could upload it manually, the problem seems to be at the skinmanager.voxelmodpack.com servers end, processing incorrectly, or the mod is posting the wrong data.

**Comment by Sollace** [comment]
@ConnorWM18 Nothing in the mod's side has changed, at least in the stable version most people are likely to be running, so I'm inclined to say the problem is with the server as skinmanager.voxelmodepack.com

That is hosted and operted by @Mumfrey, I think, so the best we can do is message him on IRC to find out what's happened. I don't currently know if anyone's tried doing that yet.

**Comment by killjoy1221** [comment]
For reference
![2018-07-21_17 57 00](https://user-images.githubusercontent.com/3409962/43040340-7e7334a8-8d0f-11e8-9100-7d036fc4ed6a.png)

Log: 
```
[17:56:55] [main/INFO]: [STDOUT]: Set SKIN C:\Users\Matthew\Pictures\zephyrbreeze.png
[17:56:58] [Thread-16/INFO]: Upload completed with: <br />
<b>Warning</b>:  file_get_contents(https://www.cloudflare.com/api_json.html): failed to open stream: HTTP request failed! HTTP/1.1 410 Gone
 in <b>C:\inetpub\wwwroot\voxelmodpack.com\skins\manager\upload.php</b> on line <b>28</b><br />
OK
```

**Comment by killjoy1221** [comment]
Ok, so the skin server actually does work, but the server is sending a bad response. Changes to your skin should be reflected still. The only issue I see is the cache probably is broken.

A quick fix would be to check the result that it says "OK" instead of just equals.

**Comment by PolyacovYury** [comment]
On recent snapshots all three servers seem to work correctly. Can this be closed?
